name: Heighten Cinematics
favicon: null
layout_spectrum: 0.43541
typography_spectrum: 0.78766
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#798287'
    - '#cecfd4'
    - '#0c0c0c'
    - '#d9833f'
  brandStrength: 0.2758607228752226
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
